# Generated by Django 3.0.3 on 2020-03-26 15:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handlers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('tweet_text', models.TextField(default=' ')),
                ('hashtags', models.CharField(max_length=300)),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Handlers')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('url_img', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=250)),
                ('num_followers', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Handlers')),
            ],
        ),
    ]
