# Generated by Django 3.0.3 on 2020-06-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='links',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='tweets',
            name='mentions',
            field=models.CharField(default=' ', max_length=300),
        ),
        migrations.AddField(
            model_name='tweets',
            name='pred',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
