# Generated by Django 3.0.3 on 2020-06-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20200608_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweets',
            name='id',
        ),
        migrations.AlterField(
            model_name='tweets',
            name='handle',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
