# Generated by Django 3.0.3 on 2020-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20200609_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweets',
            name='pred',
            field=models.IntegerField(default=0),
        ),
    ]
