# Generated by Django 3.0.3 on 2020-02-28 21:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('admin_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=20)),
                ('mobile', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('occupation', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_handle', models.CharField(max_length=50)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Admin')),
            ],
            options={
                'unique_together': {('user_name', 'twitter_handle')},
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('num_followers', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('num_following', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('blue_ticked', models.BooleanField(default=False)),
                ('twitter_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Controls')),
            ],
        ),
        migrations.CreateModel(
            name='tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=100)),
                ('tweet_text', models.TextField(default=' ')),
                ('hashtags', models.CharField(max_length=300)),
                ('twitter_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Controls')),
            ],
        ),
    ]
