# Generated by Django 3.0.3 on 2020-02-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='controls',
            unique_together=set(),
        ),
    ]
