# Generated by Django 3.0.3 on 2020-03-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0003_auto_20200321_0402'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info',
            name='url_image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
