# Generated by Django 3.0.3 on 2020-03-23 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_user_info_url_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='num_following',
        ),
        migrations.AddField(
            model_name='user_info',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
